void supercapStop(void)
{
	NRF_ADC->TASKS_STOP = 1;
	NRF_ADC->ENABLE = (ADC_ENABLE_ENABLE_Disabled << ADC_ENABLE_ENABLE_Pos);
	NRF_ADC->INTENCLR = (ADC_INTENCLR_END_Clear << ADC_INTENCLR_END_Pos);
	NRF_ADC->EVENTS_END = 0;
}
